CREATE TABLE reminders(
	rid INT NOT NULL AUTO_INCREMENT,
	expirydate DATE NOT NULL,
	uid INT,
	token VARCHAR(512) NOT NULL,
	PRIMARY KEY (rid),
	CONSTRAINT FOREIGN KEY (uid) REFERENCES users (uid)
);